version: '3.9'
services:
  sql-server:
    image: estacionamento-sql-server:latest
    container_name: estacionamento-sql-server
    build: 
        context: ../sql
        dockerfile: ./Dockerfile
    environment:
        SA_PASSWORD: "MeuDB@123"
        ACCEPT_EULA: "Y"   
    ports:
    - "1433:1433" 
  estacionamentobackoffice-api:
    image: estacionamentobackoffice-api
    build:
          context: ../src
          dockerfile: ./Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=http://*:5001
    volumes: 
        - dpkeys:/var/data_protection_keys/ 
    depends_on:
      - "sql-server"
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000"
    ports:
      - "10000:10000"
  estacionamento-backoffice-server:
      image: estacionamento/server:latest
      container_name: estacionamento-server    
      build: 
          context: ./
          dockerfile: ./nginx/Dockerfile 
      restart: always 
      ports:
          - "80:80"
          - "443:443"
      depends_on:
          - estacionamentobackoffice-api
volumes:
    dpkeys:     