version: '3.9'
services:
  estacionamentobackoffice-api:
    image: estacionamentobackoffice-api
    build:
          context: ../src
          dockerfile: ./Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://*:5001
    volumes: 
        - dpkeys:/var/data_protection_keys/ 
    depends_on:
      - "sqlserver"
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000"
    ports:
      - "10000:10000"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        SA_PASSWORD: "SqlServer2019!"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Developer"
    ports:
        - "1433:1433"
  estacionamento-backoffice-server:
      image: estacionamento/server:latest
      container_name: estacionamento-server    
      build: 
          context: ./
          dockerfile: ./nginx/Dockerfile 
      restart: always 
      ports:
          - "80:80"
          - "443:443"
      depends_on:
          - estacionamentobackoffice-api
volumes:
    dpkeys:     